MODEL:
  TYPE: vit
  NUM_CLASSES: 20557
VIT:
  PATCH_SIZE: 16
  STEM_TYPE: "conv"
  C_STEM_KERNELS: [3, 3, 3, 3, 3, 3, 3, 3, 1]
  C_STEM_STRIDES: [2, 2, 1, 2, 1, 1, 2, 1, 1]
  C_STEM_DIMS: [64, 128, 128, 256, 256, 256, 512, 512, 1152]
  NUM_LAYERS: 21
  NUM_HEADS: 18
  HIDDEN_DIM: 1152
  MLP_DIM: 4608
  CLASSIFIER_TYPE: token
OPTIM:
  OPTIMIZER: adamw
  LR_POLICY: cos
  BASE_LR: 0.0012
  MIN_LR: 0.005
  MAX_EPOCH: 90
  WEIGHT_DECAY: 0.28
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1.0e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
LN:
  EPS: 1e-6
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
BN:
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet-21k
  IM_SIZE: 224
  BATCH_SIZE: 4096
  MIXED_PRECISION: True
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
TEST:
  DATASET: imagenet-21k
  IM_SIZE: 256
  BATCH_SIZE: 4096
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 128
