MODEL:
  TYPE: vit
  NUM_CLASSES: 1000
VIT:
  PATCH_SIZE: 16
  STEM_TYPE: "patchify"
  NUM_LAYERS: 32
  NUM_HEADS: 16
  HIDDEN_DIM: 1280
  MLP_DIM: 5120
  CLASSIFIER_TYPE: "pooled"
BN:
  USE_PRECISE_STATS: False
OPTIM:
  OPTIMIZER: adamw
  LR_POLICY: cos
  BASE_LR: 0.001
  MIN_LR: 0.005
  MAX_EPOCH: 100
  WEIGHT_DECAY: 0.24
  WARMUP_EPOCHS: 5
  EMA_ALPHA: 1.0e-5
  EMA_UPDATE_PERIOD: 32
  BIAS_USE_CUSTOM_WEIGHT_DECAY: True
  BIAS_CUSTOM_WEIGHT_DECAY: 0.
  MTA: True
LN:
  EPS: 1e-6
  USE_CUSTOM_WEIGHT_DECAY: True
  CUSTOM_WEIGHT_DECAY: 0.
TRAIN:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 128
  MIXUP_ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  LABEL_SMOOTHING: 0.1
  AUGMENT: AutoAugment
  MIXED_PRECISION: True
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 128
DATA_LOADER:
  NUM_WORKERS: 10
LOG_PERIOD: 100
NUM_GPUS: 8
LAUNCH:
  GPU_TYPE: "volta32gb"
  MODE: "local"
FSDP:
  ENABLED: True
  DO_NOT_RESHARD_AFTER_FW: True
  MIXED_PRECISION: True
  LAYER_NORM_FP32: True
